CURRENCIES = {
    'د.إ': ['AED'],
    'AR$': ['ARS'],
    '$': ['AUD', 'CAD', 'NZD', 'SGD', 'USD'],
    'KM': ['BAM'],
    '৳': ['BDT'],
    'BGN': ['BGN'],
    '.د.ب': ['BHD'],
    'Bs.': ['BOB'],
    'R$': ['BRL'],
    'CHF': ['CHF'],
    'CL$': ['CLP'],
    '¥': ['CNY', 'JPY'],
    'CO$': ['COP'],
    'Kč': ['CZK'],
    'kr': ['DKK', 'ISK', 'NOK', 'SEK'],
    'E£': ['EGP'],
    '€': ['EUR'],
    '£': ['GBP'],
    'GH₵': ['GHS'],
    'HK$': ['HKD'],
    'Ft': ['HUF'],
    'Rp': ['IDR'],
    '₪': ['ILS'],
    '₹': ['INR'],
    'ع.د': ['IQD'],
    'د.ا': ['JOD'],
    'KSh': ['KES'],
    '៛': ['KHR'],
    '₩': ['KRW'],
    'د.ك': ['KWD'],
    '₭': ['LAK'],
    'ل.ل': ['LBP'],
    'Rs': ['LKR', 'PKR'],
    'MAD': ['MAD'],
    'K': ['MMK'],
    '₮': ['MNT'],
    'MOP$': ['MOP'],
    'MX$': ['MXN'],
    'RM': ['MYR'],
    '₦': ['NGN'],
    'रू': ['NPR'],
    'ر.ع.': ['OMR'],
    'S/': ['PEN'],
    '₱': ['PHP'],
    'zł': ['PLN'],
    '₲': ['PYG'],
    'ر.ق': ['QAR'],
    'lei': ['RON'],
    'дин.': ['RSD'],
    '₽': ['RUB'],
    '﷼': ['SAR'],
    '฿': ['THB'],
    '₺': ['TRY'],
    'NT$': ['TWD'],
    'TSh': ['TZS'],
    '₴': ['UAH'],
    'USh': ['UGX'],
    '$U': ['UYU'],
    '₫': ['VND'],
    'ZAR': ['ZAR']
}

ICON_CHOICES = [
    # General & Finance
    ('flag', 'Objective'),
    ('coins', 'Coins'),
    ('money', 'Cash'),
    ('credit-card', 'Credit Card'),
    ('receipt', 'Bills'),
    ('wallet', 'Wallet'),
    ('piggy-bank', 'Savings'),
    ('vault', 'Vault'),
    ('bank', 'Bank'),
    ('chart-bar', 'Investment'),
    ('shield-check', 'Insurance'),

    # Travel
    ('airplane-tilt', 'Travel'),
    ('backpack', 'Backpack'),
    ('suitcase-rolling', 'Luggage'),
    ('building', 'Hotel'),
    ('tent', 'Camping'),
    ('island', 'Island'),

    # Food & Dining
    ('shopping-cart-simple', 'Shopping'),
    ('fork-knife', 'Food'),
    ('gift', 'Gifts'),
    ('cake', 'Celebration'),
    ('storefront', 'Store'),

    # Home & Family
    ('house-line', 'House'),
    ('armchair', 'Furniture'),
    ('paint-roller', 'Renovation'),
    ('heart', 'Relationship'),
    ('paw-print', 'Pets'),
    ('baby-carriage', 'Kids'),
    ('person', 'Person'),

    # Education & Career
    ('books', 'Books'),
    ('certificate', 'Certificate'),
    ('graduation-cap', 'Education'),
    ('briefcase', 'Business'),

    # Hobbies & Entertainment
    ('ticket', 'Events'),
    ('palette', 'Art'),
    ('music-notes', 'Music'),
    ('game-controller', 'Gaming'),
    ('barbell', 'Gym'),

    # Gadgets & Tech
    ('t-shirt', 'Shirt'),
    ('pants', 'Pants'),
    ('sneaker', 'Shoes'),
    ('watch', 'Watch'),
    ('headphones', 'Headphones'),
    ('camera', 'Photography'),
    ('device-mobile', 'Smartphone'),
    ('laptop', 'Laptop'),
    ('desktop', 'Desktop'),
    ('television', 'TV'),

    # Vehicles
    ('bicycle', 'Bicycle'),
    ('motorcycle', 'Motorcycle'),
    ('car', 'Car'),
    ('wrench', 'Maintenance'),

    # Health & Emergency
    ('warning-octagon', 'Emergency Fund'),
    ('first-aid', 'Medical'),
    ('heartbeat', 'Health'),
]
